INSERT INTO streaming.video (id,created_at,content_type,thumbnail,title,url)
VALUES
	 ('asd','2023-09-05 17:28:02','video/youtube','https://img.youtube.com/vi/dwOxkCypE7M/mqdefault.jpg','ScyllaDB Cloud Terraform provider #3: Add CIDR block to the allowlist','https://www.youtube.com/watch?v=dwOxkCypE7M');

INSERT INTO streaming.video (id,created_at,content_type,thumbnail,title,url)
VALUES
	 ('qwe','2023-09-06 16:18:23','video/youtube','https://img.youtube.com/vi/sA8Rqpggr30/mqdefault.jpg',' ScyllaDB Cloud Terraform provider #2: Create new cluster ','https://www.youtube.com/watch?v=sA8Rqpggr30');